#!/bin/bash
EXTRA_ARGS=""
if [ "$MESOS_HOME" != "" ]; then
  EXTRA_ARGS="-Djava.library.path=$MESOS_HOME/lib/java"
fi
export SPARK_HOME=$(cd "$(dirname $0)/.."; pwd)
java -Xmx800M --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/sun.net.www.protocol.https=ALL-UNNAMED $EXTRA_ARGS -Dsbt.boot.properties="$SPARK_HOME/sbt/sbt.boot.properties" -jar $SPARK_HOME/sbt/sbt-launch-*.jar "$@"
